apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alerts
data:
  alerts.yml: |-
    groups:
    - name: rhythm-ai.rules
      rules:
      - alert: HighInferenceLatency
        expr: histogram_quantile(0.95, sum(rate(response_time_seconds_bucket{job="rhythm-ai-inference"}[5m])) by (le)) > 2
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High 95th percentile inference latency"
          description: "95th percentile inference latency is > 2s for 5m"
      - alert: PodOOMKilled
        expr: kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Pod OOMKilled"
          description: "A Rhythm AI pod was killed due to Out Of Memory."