name: Train Rhythm AI Model

on:
  push:
    branches: [main, master]
    paths:
      - "model-training/**"
      - ".github/workflows/github_actions_train.yml"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1
          pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r model-training/requirements.txt

      - name: Preprocess Data (optional)
        run: |
          python model-training/preprocess.py

      - name: Train Model
        run: |
          python model-training/train.py

      - name: Evaluate Model
        run: |
          python model-training/evaluate.py

      - name: Upload Checkpoints to Artifact Store
        uses: actions/upload-artifact@v4
        with:
          name: checkpoints
          path: model-training/models/checkpoints/

      - name: Upload Logs to Artifact Store
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: model-training/logs/